### ISSUE TITLE
Kontaktanfrage

### ISSUE THREAD

**Issue by gixxi** [twiddles/jftrl#1]
hey meister,

anders komme ich nicht an dich ran - als über diesen issue :)

habe auf github gesehen, dass du algorithmen für kaggle entwickelst resp. dort an wettbewerben teilnimmst. cool.

wie gehts Dir so? Alles smooth bei der SBB?

Liebe Grüsse
Christian

**Comment by twiddles** [comment]
:smile: :+1:  Kontaktaufnahme via Issue, das nenn' ich mal eine standesgerechte Art der Kommunikation für Software Entwickler ;)

Danke, danke, läuft super. Bei dir auch? Wechsle SBB-intern in ein neues BigData-Kernteam, dass sich auch mit solchen Themen wie bei Kaggle beschäftigt. Freu mich jedenfalls riesig :)

Hast du einen Xing/Linkedin Account oder E-Mail Adresse? mvonrohr at gmx dot ch

Ich schliess' den Issue mal ;)

Beste Grüsse
